#include "constants/species.h"
#include "constants/forms.h"
#include "field/field_system.h"
#include "follower.h"
#include "generated/genders.h"
#include "generated/object_events_gfx.h"
#include "map_object.h"
#include "map_header.h"
#include "party.h"
#include "pokemon.h"
#include "unk_02054884.h"

#define FOLLOW_MON_OBJECT_PARAM_SPECIES 0
#define FOLLOW_MON_OBJECT_PARAM_FORM    1
#define FOLLOW_MON_OBJECT_PARAM_FLAGS   2

#define FOLLOW_MON_OBJECT_FLAG_SHINY        (1 << 0)
#define FOLLOW_MON_OBJECT_FLAG_ACTIVE       (1 << 1)
#define FOLLOW_MON_OBJECT_FLAG_UNK_2        (1 << 2)
#define FOLLOW_MON_OBJECT_STATE_8_SHIFT     8
#define FOLLOW_MON_OBJECT_STATE_8_MASK      (3 << FOLLOW_MON_OBJECT_STATE_8_SHIFT)
#define FOLLOW_MON_OBJECT_STATE_10_SHIFT    10
#define FOLLOW_MON_OBJECT_STATE_10_MAX      23
#define FOLLOW_MON_OBJECT_STATE_10_MASK     (0x3F << FOLLOW_MON_OBJECT_STATE_10_SHIFT)
#define FOLLOW_MON_OBJECT_FLAGS_SAVE_MASK   0x7FFF

#define FOLLOW_MON_BOUNCE_FAST 0x00
#define FOLLOW_MON_BOUNCE_MED  0x10
#define FOLLOW_MON_BOUNCE_SLOW 0x11

#define FOLLOW_MON_CAN_ENTER 0
#define FOLLOW_MON_NO_ENTRY  1

#define FOLLOW_MON_INFO(tooTall_, movementFlags_) { 0, tooTall_, movementFlags_, 0 }

static FollowMonInfo sFollowMonDefaultInfo = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_FAST);
static FollowMonInfo sFollowMonShayminSkyInfo = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW);
static FollowMonInfo sFollowMonGiratinaOriginInfo = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW);

static FollowMonInfo sFollowMonInfo[SPECIES_ARCEUS + 1] = {
    [SPECIES_BUTTERFREE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_BEEDRILL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_PIDGEOTTO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_PIDGEOT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_FEAROW] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_ZUBAT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_GOLBAT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_VENOMOTH] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_DIGLETT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DUGTRIO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_ABRA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_TENTACOOL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_TENTACRUEL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MAGNEMITE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MAGNETON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GASTLY] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_HAUNTER] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_KOFFING] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_WEEZING] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_HORSEA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SEADRA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GOLDEEN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SEAKING] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GYARADOS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_LAPRAS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_PORYGON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_KABUTO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_AERODACTYL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_ARTICUNO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_ZAPDOS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_MOLTRES] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_DRAGONITE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_MEW] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_NOCTOWL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_LEDYBA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_LEDIAN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_CROBAT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_CHINCHOU] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_LANTURN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_TOGETIC] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_HOPPIP] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SKIPLOOM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_JUMPLUFF] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_YANMA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_MISDREAVUS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_UNOWN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GLIGAR] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_STEELIX] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, 1),
    [SPECIES_QWILFISH] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_REMORAID] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MANTINE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SKARMORY] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_KINGDRA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_PORYGON2] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_LUGIA] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_HO_OH] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_CELEBI] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_BEAUTIFLY] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_DUSTOX] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SWELLOW] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_WINGULL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_PELIPPER] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SURSKIT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MASQUERAIN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_NINJASK] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SHEDINJA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MEDITITE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_VOLBEAT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_ILLUMISE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_CARVANHA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SHARPEDO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_WAILMER] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_WAILORD] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_VIBRAVA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_FLYGON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SWABLU] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_ALTARIA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_LUNATONE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_SOLROCK] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_WHISCASH] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_BALTOY] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_CLAYDOL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_ANORITH] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_FEEBAS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MILOTIC] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_CASTFORM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SHUPPET] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DUSKULL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_CHIMECHO] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_CLAMPERL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_HUNTAIL] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GOREBYSS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_RELICANTH] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_LUVDISC] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_BELDUM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_METANG] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_LATIAS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_LATIOS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_KYOGRE] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_GROUDON] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_FAST),
    [SPECIES_RAYQUAZA] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_JIRACHI] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DEOXYS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_STARAVIA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_STARAPTOR] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_MOTHIM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_COMBEE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_VESPIQUEN] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DRIFLOON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DRIFBLIM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MISMAGIUS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_BRONZOR] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_BRONZONG] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_SPIRITOMB] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_CARNIVINE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_FINNEON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_LUMINEON] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MANTYKE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MAGNEZONE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_TOGEKISS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_SLOW),
    [SPECIES_YANMEGA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_GLISCOR] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_PORYGON_Z] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_FROSLASS] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_ROTOM] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_UXIE] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_MESPRIT] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_AZELF] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DIALGA] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_FAST),
    [SPECIES_PALKIA] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_FAST),
    [SPECIES_REGIGIGAS] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_FAST),
    [SPECIES_GIRATINA] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_FAST),
    [SPECIES_CRESSELIA] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_DARKRAI] = FOLLOW_MON_INFO(FOLLOW_MON_CAN_ENTER, FOLLOW_MON_BOUNCE_MED),
    [SPECIES_ARCEUS] = FOLLOW_MON_INFO(FOLLOW_MON_NO_ENTRY, FOLLOW_MON_BOUNCE_SLOW),
};

static u8 FollowMon_GetMaxFormIndex(u16 species)
{
  switch (species) {
  case SPECIES_PICHU:
    return 1;
  case SPECIES_UNOWN:
    return UNOWN_FORM_COUNT - 1;
  case SPECIES_DEOXYS:
    return DEOXYS_FORM_COUNT - 1;
  case SPECIES_BURMY:
    return BURMY_FORM_COUNT - 1;
  case SPECIES_WORMADAM:
    return WORMADAM_FORM_COUNT - 1;
  case SPECIES_SHELLOS:
    return SHELLOS_FORM_COUNT - 1;
  case SPECIES_GASTRODON:
    return GASTRODON_FORM_COUNT - 1;
  case SPECIES_ROTOM:
    return ROTOM_FORM_COUNT - 1;
  case SPECIES_GIRATINA:
    return GIRATINA_FORM_COUNT - 1;
  case SPECIES_SHAYMIN:
    return SHAYMIN_FORM_COUNT - 1;
  case SPECIES_ARCEUS:
    return ARCEUS_FORM_COUNT - 1;
  default:
    return 0;
  }
}

static u8 FollowMon_GetGraphicsSlotCount(u16 species)
{
  if (FollowMon_HasGenderDifference(species)) {
    return 2;
  }

  return FollowMon_GetMaxFormIndex(species) + 1;
}

int FollowMon_GetMetadataIndex(u16 species)
{
  int index = 0;
  int i;

  if (species == SPECIES_NONE || species > SPECIES_ARCEUS) {
    return SPECIES_NONE;
  }

  for (i = SPECIES_BULBASAUR; i < species; i++) {
    index += FollowMon_GetGraphicsSlotCount(i);
  }

  return index;
}

int FollowMon_GetFormCount(u16 species)
{
  switch (species) {
  case SPECIES_PICHU:
    return 2;
  case SPECIES_UNOWN:
    return UNOWN_FORM_COUNT;
  case SPECIES_DEOXYS:
    return DEOXYS_FORM_COUNT;
  case SPECIES_BURMY:
    return BURMY_FORM_COUNT;
  case SPECIES_WORMADAM:
    return WORMADAM_FORM_COUNT;
  case SPECIES_SHELLOS:
    return SHELLOS_FORM_COUNT;
  case SPECIES_GASTRODON:
    return GASTRODON_FORM_COUNT;
  case SPECIES_ROTOM:
    return ROTOM_FORM_COUNT;
  case SPECIES_GIRATINA:
    return GIRATINA_FORM_COUNT;
  case SPECIES_SHAYMIN:
    return SHAYMIN_FORM_COUNT;
  case SPECIES_ARCEUS:
    return ARCEUS_FORM_COUNT;
  default:
    return 1;
  }
}

BOOL FollowMon_HasGenderDifference(u16 species)
{
  switch (species) {
  case SPECIES_VENUSAUR:
  case SPECIES_PIKACHU:
  case SPECIES_MEGANIUM:
  case SPECIES_WOBBUFFET:
  case SPECIES_STEELIX:
  case SPECIES_HERACROSS:
  case SPECIES_COMBEE:
  case SPECIES_GIBLE:
  case SPECIES_GABITE:
  case SPECIES_GARCHOMP:
  case SPECIES_HIPPOPOTAS:
  case SPECIES_HIPPOWDON:
    return TRUE;
  default:
    return FALSE;
  }
}

FollowMonInfo *FollowMon_GetMetadata(u16 species, u8 form)
{
  form = Pokemon_SanitizeFormId(species, form);

  if (species == SPECIES_SHAYMIN && form == 1) {
    return &sFollowMonShayminSkyInfo;
  }

  if (species == SPECIES_GIRATINA && form == 1) {
    return &sFollowMonGiratinaOriginInfo;
  }

  if (species == SPECIES_NONE || species > SPECIES_ARCEUS) {
    return NULL;
  }

  if (sFollowMonInfo[species].tooTall == 0 && sFollowMonInfo[species].movementFlags == 0 && sFollowMonInfo[species].unk0 == 0 && sFollowMonInfo[species].unk3 == 0) {
    return &sFollowMonDefaultInfo;
  }

  return &sFollowMonInfo[species];
}

int FollowMon_GetObjectGraphicsID(u16 species, u8 form, u8 gender)
{
  (void)gender;

  if (species == SPECIES_NONE || species > SPECIES_ARCEUS) {
    return OBJ_EVENT_GFX_PIKACHU;
  }

  switch (species) {
  case SPECIES_PIKACHU:
    return OBJ_EVENT_GFX_PIKACHU;
  case SPECIES_CLEFAIRY:
    return OBJ_EVENT_GFX_CLEFAIRY;
  case SPECIES_JIGGLYPUFF:
    return OBJ_EVENT_GFX_JIGGLYPUFF;
  case SPECIES_PSYDUCK:
    return OBJ_EVENT_GFX_PSYDUCK;
  case SPECIES_TORCHIC:
    return OBJ_EVENT_GFX_TORCHIC;
  case SPECIES_SKITTY:
    return OBJ_EVENT_GFX_SKITTY;
  case SPECIES_UXIE:
    return OBJ_EVENT_GFX_UXIE;
  case SPECIES_MESPRIT:
    return OBJ_EVENT_GFX_MESPRIT;
  case SPECIES_AZELF:
    return OBJ_EVENT_GFX_AZELF;
  case SPECIES_DIALGA:
    return OBJ_EVENT_GFX_DIALGA;
  case SPECIES_PALKIA:
    return OBJ_EVENT_GFX_PALKIA;
  case SPECIES_ARCEUS:
    return OBJ_EVENT_GFX_ARCEUS;
  case SPECIES_DARKRAI:
    return OBJ_EVENT_GFX_DARKRAI;
  case SPECIES_SHAYMIN:
    return OBJ_EVENT_GFX_SHAYMIN;
  case SPECIES_CRESSELIA:
    return OBJ_EVENT_GFX_CRESSELIA;
  case SPECIES_GIRATINA:
    if (form == GIRATINA_FORM_ORIGIN) {
      return OBJ_EVENT_GFX_GIRATINA_ORIGIN;
    }
    return OBJ_EVENT_GFX_GIRATINA_ALTERED;
  case SPECIES_HEATRAN:
    return OBJ_EVENT_GFX_HEATRAN;
  case SPECIES_STARLY:
    return OBJ_EVENT_GFX_STARLY;
  case SPECIES_REGIGIGAS:
    return OBJ_EVENT_GFX_REGIGIGAS;
  case SPECIES_DRIFLOON:
    return OBJ_EVENT_GFX_DRIFLOON;
  case SPECIES_MAGIKARP:
    return OBJ_EVENT_GFX_MAGIKARP;
  case SPECIES_PACHIRISU:
    return OBJ_EVENT_GFX_PACHIRISU;
  case SPECIES_SHROOMISH:
    return OBJ_EVENT_GFX_SHROOMISH;
  case SPECIES_BUNEARY:
    return OBJ_EVENT_GFX_BUNEARY;
  case SPECIES_HAPPINY:
    return OBJ_EVENT_GFX_HAPPINY;
  case SPECIES_MACHOP:
    return OBJ_EVENT_GFX_MACHOP;
  case SPECIES_TURTWIG:
    return OBJ_EVENT_GFX_TURTWIG;
  case SPECIES_GROTLE:
    return OBJ_EVENT_GFX_GROTLE;
  case SPECIES_TORTERRA:
    return OBJ_EVENT_GFX_TORTERRA;
  case SPECIES_CHIMCHAR:
    return OBJ_EVENT_GFX_CHIMCHAR;
  case SPECIES_MONFERNO:
    return OBJ_EVENT_GFX_MONFERNO;
  case SPECIES_INFERNAPE:
    return OBJ_EVENT_GFX_INFERNAPE;
  case SPECIES_PIPLUP:
    return OBJ_EVENT_GFX_PIPLUP;
  case SPECIES_PRINPLUP:
    return OBJ_EVENT_GFX_PRINPLUP;
  case SPECIES_EMPOLEON:
    return OBJ_EVENT_GFX_EMPOLEON;
  case SPECIES_CROAGUNK:
    return OBJ_EVENT_GFX_CROAGUNK;
  case SPECIES_ROTOM:
    switch (form) {
    case ROTOM_FORM_HEAT:
      return OBJ_EVENT_GFX_ROTOM_HEAT;
    case ROTOM_FORM_WASH:
      return OBJ_EVENT_GFX_ROTOM_WASH;
    case ROTOM_FORM_FROST:
      return OBJ_EVENT_GFX_ROTOM_FROST;
    case ROTOM_FORM_FAN:
      return OBJ_EVENT_GFX_ROTOM_FAN;
    case ROTOM_FORM_MOW:
      return OBJ_EVENT_GFX_ROTOM_MOW;
    default:
      break;
    }
    break;
  }

  return OBJ_EVENT_GFX_PIKACHU;
}

static int FollowMon_GetObjectFlags(MapObject *mapObj)
{
  return MapObject_GetDataAt(mapObj, FOLLOW_MON_OBJECT_PARAM_FLAGS) & FOLLOW_MON_OBJECT_FLAGS_SAVE_MASK;
}

static void FollowMon_SetObjectFlags(MapObject *mapObj, int flags)
{
  MapObject_SetDataAt(mapObj, flags & FOLLOW_MON_OBJECT_FLAGS_SAVE_MASK, FOLLOW_MON_OBJECT_PARAM_FLAGS);
}

static void FollowMon_SetObjectFlag(MapObject *mapObj, int flag, BOOL enabled)
{
  int flags = FollowMon_GetObjectFlags(mapObj);

  flags &= ~flag;

  if (enabled) {
    flags |= flag;
  }

  FollowMon_SetObjectFlags(mapObj, flags);
}

static void FollowMon_SetObjectShiny(MapObject *mapObj, BOOL isShiny)
{
  FollowMon_SetObjectFlag(mapObj, FOLLOW_MON_OBJECT_FLAG_SHINY, isShiny);
}

static void FollowMon_SetObjectFormParams(MapObject *mapObj, u16 species, u8 form)
{
  FollowMonInfo *info = FollowMon_GetMetadata(species, form);
  int params = 0;

  if (info != NULL) {
    params = (info->tooTall << 8) | info->movementFlags;
  }

  MapObject_SetDataAt(mapObj, params, FOLLOW_MON_OBJECT_PARAM_FORM);
}

void FollowMon_SetObjectParams(MapObject *mapObj, u16 species, u8 form, BOOL isShiny)
{
  MapObject_SetDataAt(mapObj, species, FOLLOW_MON_OBJECT_PARAM_SPECIES);
  FollowMon_SetObjectFormParams(mapObj, species, form);
  FollowMon_SetObjectShiny(mapObj, isShiny);
}

u16 FollowMon_GetObjectSpecies(MapObject *mapObj)
{
  return MapObject_GetDataAt(mapObj, FOLLOW_MON_OBJECT_PARAM_SPECIES);
}

BOOL FollowMon_ObjectIsShiny(MapObject *mapObj)
{
  return (FollowMon_GetObjectFlags(mapObj) & FOLLOW_MON_OBJECT_FLAG_SHINY) != 0;
}

void FollowMon_SetObjectActive(MapObject *mapObj, BOOL active)
{
  MapObject_SetHidden(mapObj, !active);
  sub_02062DB4(mapObj, active);
  FollowMon_SetObjectFlag(mapObj, FOLLOW_MON_OBJECT_FLAG_ACTIVE, active);
}

BOOL FollowMon_ObjectIsActive(MapObject *mapObj)
{
  return (FollowMon_GetObjectFlags(mapObj) & FOLLOW_MON_OBJECT_FLAG_ACTIVE) != 0;
}

void FollowMon_Clear(FollowMon *followMon)
{
  followMon->mapObj = NULL;
  followMon->animation = 0;
  followMon->x = 0;
  followMon->z = 0;
  followMon->species = SPECIES_NONE;
  followMon->form = 0;
  followMon->gender = 0;
  followMon->isFollowing = 0;
  followMon->isShiny = FALSE;
  followMon->needReset = 0;
  followMon->commandState = FOLLOW_MON_ANIM_NONE;
}

void FollowMon_SetInfo(FollowMon *followMon, u16 species, u8 form, u8 gender, BOOL isShiny)
{
  followMon->species = species;
  followMon->form = form;
  followMon->isShiny = isShiny;
  followMon->gender = gender;
}

BOOL FollowMon_IsActive(FieldSystem *fieldSystem)
{
  // TODO check party too
  return fieldSystem->followMon.isFollowing;
}

void FollowMon_RequestReset(FollowMon *followMon)
{
  followMon->needReset = 1;
}

void FollowMonMood_SetPokemon(FollowMonMood *mood, Pokemon *mon)
{
  u16 species;
  int personality;

  if (mon == NULL) {
      return;
  }

  species = Pokemon_GetValue(mon, MON_DATA_SPECIES, NULL);
  personality = Pokemon_GetValue(mon, MON_DATA_PERSONALITY, NULL);

  if (species == SPECIES_NONE) {
      return;
  }

  if (!mood->initialized || mood->species != species || mood->personality != personality)
  {
      mood->species = species;
      mood->personality = personality;
      mood->initialized = TRUE;
      // TODO reset follower mood
  }

  mood->mon = mon;
}

void FollowMonMood_SetValue(FollowMonMood *mood, s8 value)
{
  // TODO
}

s8 FollowMonMood_GetValue(FollowMonMood *mood)
{
  return 0; // TODO
}

void FollowMonMood_DriftTowardNeutral(FollowMonMood *mood)
{
  // TODO
}

BOOL FollowMon_CanFollow(u16 species, int mapId)
{
  if (species == SPECIES_NONE || species > SPECIES_ARCEUS) {
    return FALSE;
  }

  if (MapHeader_IsUnionRoom(mapId) || MapHeader_IsPokemonCenter2F(mapId)) {
    return FALSE;
  }

  return TRUE; // TODO replace with HGSS map permission data.
}

Pokemon *FollowMon_GetLeadPokemon(Party *party)
{
  if (Party_GetCurrentCount(party) == 0) {
    return NULL;
  }
  if (Party_AliveMonsCount(party) == 0) {
    return Party_GetPokemonBySlotIndex(party, 0);
  }
  return Party_FindFirstEligibleBattler(party);
}
