#ifndef POKEPLATINUM_FOLLOW_MON_FEATURE_H
#define POKEPLATINUM_FOLLOW_MON_FEATURE_H

#define FOLLOW_MON_ENABLED 0
#define FOLLOW_MON_SPAWN_ENABLED 1
#define FOLLOW_MON_SAVE_ENABLED 1

#endif // POKEPLATINUM_FOLLOW_MON_FEATURE_H
